#!/bin/sh
#------------------------------------------------------------------------
# shell script for running the test program for the Java NeXus API
#
# Version for Redhat 6.2
#
# Mark Koennecke, October 2000
#------------------------------------------------------------------------
java -classpath /usr/local/jdk118_v1/lib/classes.zip:../jnexus.jar:. \
 -Dneutron.nexus.JNEXUSLIB=$HOME/nt/k/src/NeXus/jnexus/bin/rh62/libjnexus.so TestJapi
 
