$!
$! $Id$
$!
$! Build comamnd file for VMS
$!
$ SET VERIFY
$ DEFINE HDF_ROOT AXPLIB$DISK:[HDF.]	! where you installed HDF, trailing "." is needed
$ CC/INCLUDE=HDF_ROOT:[INCLUDE] NAPI.C
$ CC/INCLUDE=HDF_ROOT:[INCLUDE] NAPI_TEST.C
$ FORTRAN NAPIF.F
$ FORTRAN NAPIF_TEST.F
$ LINK NAPI_TEST,NAPI,HDF_ROOT:[LIB]MFHDF/LIB,DF/LIB,LIBZ/LIB
$ LINK NAPIF_TEST,NAPIF,NAPI,HDF_ROOT:[LIB]MFHDF/LIB,DF/LIB,LIBZ/LIB
