#!/bin/sh
#
# $Id$
#
# Create links needed by MinGW to various libraries that exist on
# the windows file system
#
for i in /usr/local /usr/local/bin /usr/local/lib \
         /usr/local/hdf4 /usr/local/hdf4/lib \
         /usr/local/hdf5 /usr/local/hdf5/lib ; do
    [ -d $i ] || mkdir $i
done
#
# Change these to the locations of the various libraries
# on the windows system
#
HDF4ROOT="/c/program files/hdf/42r1-win"
HDF5ROOT="/c/program files/hdf/5-164-win"
ZLIBROOT="/c/program files/hdf/zlib122-windows"
SZIPROOT="/c/program files/hdf/szip20-win-xp-enc"
XML2ROOT="/c/program files/libxml2-2.6.20.win32"
ICONVROOT="/c/program files/iconv-1.9.1.win32"
#
ln -sf "$HDF4ROOT/release/include" /usr/local/hdf4/include
ln -sf "$HDF4ROOT/release/dll/hm421m.dll" /usr/local/hdf4/lib/libmfhdf.dll
ln -sf "$HDF4ROOT/release/dll/hd421m.dll" /usr/local/hdf4/lib/libdf.dll
ln -sf "$HDF5ROOT/include" /usr/local/hdf5/include
ln -sf "$HDF5ROOT/dll/hdf5dll.dll" /usr/local/hdf5/lib/libhdf5.dll
ln -sf "$ZLIBROOT/zlib1.dll" /usr/local/lib/libz.dll
ln -sf "$SZIPROOT/dll/szlibdll.dll" /usr/local/lib/libsz.dll
ln -sf "$XML2ROOT/bin/libxml2.dll" /usr/local/lib/libxml2.dll
ln -sf "$XML2ROOT/include/libxml" /usr/local/include/libxml
ln -sf "$ICONVROOT/include/iconv.h" /usr/local/include/iconv.h
ln -sf "$ICONVROOT/bin/iconv.dll" /usr/local/lib/libiconv.dll
#JPEGROOT="$HDFROOT/jpeg-6b"
#ln -s "$JPEGROOT/libjpeg.lib" /usr/local/lib/libjpeg.a
