#!/bin/sh
#
# $Id$
#
# Create links needed by MinGW to various libraries that exist on
# the windows file system. The basic idea is that we link in the Windows
# installed versions of these libraries and make then look like 
# standard unix libraries for configure to pick up. An alternative would be
# to build the HDF etc. libraries from source under MinGW
#
# first create the /usr/local hierarchy 
#
for i in /usr/local /usr/local/include /usr/local/bin /usr/local/lib \
         /usr/local/hdf4 /usr/local/hdf4/lib \
         /usr/local/hdf5 /usr/local/hdf5/lib ; do
    [ -d $i ] || mkdir $i
done
#
### BEGIN USER CONFIGURATION ###
#
# CHANGE THESE TO THE LOCATIONS OF THE VARIOUS LIBRARIES
# ON THE WINDOWS SYSTEM
#
# For Mini-XML you should download the source from 
# http://www.easysw.com/~mike/mxml/ and then compile directly 
# under MinGW to install the library into /usr/local/lib
#
# HDF4 windows binary install (from http://hdf.ncsa.uiuc.edu)
#
ln -sf "/c/program files/hdf/42r1-win/release/include" /usr/local/hdf4/include
ln -sf "/c/program files/hdf/42r1-win/release/dll/hd421m.dll" /usr/local/hdf4/lib/libdf.dll
ln -sf "/c/program files/hdf/42r1-win/release/dll/hm421m.dll" /usr/local/hdf4/lib/libmfhdf.dll
#
# HDF5 windows binary install  (from http://hdf.ncsa.uiuc.edu)
#
ln -sf "/c/program files/hdf/5-164-win/include" /usr/local/hdf5/include
ln -sf "/c/program files/hdf/5-164-win/dll/hdf5dll.dll" /usr/local/hdf5/lib/libhdf5.dll
#
# ZLIB (from http://www.gzip.org/zlib/)
#
ln -sf "/c/program files/hdf/zlib122-windows/zlib1.dll" /usr/local/lib/libz.dll
#
# SZIP from http://hdf.ncsa.uiuc.edu/
#
ln -sf "/c/program files/hdf/szip20-win-xp-enc/dll/szlibdll.dll" /usr/local/lib/libsz.dll
#
# LIBXML2 (optional; only needed for NXtranslate) from http://xmlsoft.org/
#
ln -sf "/c/program files/libxml2-2.6.20.win32/bin/libxml2.dll" /usr/local/lib/libxml2.dll
ln -sf "/c/program files/libxml2-2.6.20.win32/include/libxml" /usr/local/include/libxml
#
# LIBICONV (optional; only needed for NXtranslate)
#
ln -sf "/c/program files/iconv-1.9.1.win32/include/iconv.h" /usr/local/include/iconv.h
ln -sf "/c/program files/iconv-1.9.1.win32/bin/iconv.dll" /usr/local/lib/libiconv.dll
#
### END OF USER CONFIGURATION ###
#
