;;;;;;;;; !include "EnvVarUpdate.nsh"
${EnvVarUpdate} $0 "NEXUSDIR" "P" "HKCU" "$INSTDIR"
${EnvVarUpdate} $0 "NEXUSDIR${NEXUSENVSUFFIX}" "P" "HKCU" "$INSTDIR"
${EnvVarUpdate} $0 "PATH" "P" "HKCU" "$INSTDIR\bin"
${EnvVarUpdate} $0 "LIB" "P" "HKCU" "$INSTDIR\lib"
${EnvVarUpdate} $0 "INCLUDE" "P" "HKCU" "$INSTDIR\include"
${EnvVarUpdate} $0 "PYTHONPATH" "P" "HKCU" "$INSTDIR\python;$INSTDIR\bin"
${EnvVarUpdate} $0 "CLASSPATH" "P" "HKCU" "$INSTDIR\java\jnexus.jar"