#====================================================================
#  NeXus - Neutron & X-ray Common Data Format
#  
#  $Id: Makefile.am 961 2007-09-04 12:31:49Z Freddie Akeroyd $
#
#  Top level scons file for coordinating NeXus build
#  
#  Copyright (C) 2008 Freddie Akeroyd
#  
#  This library is free software; you can redistribute it and/or
#  modify it under the terms of the GNU Lesser General Public
#  License as published by the Free Software Foundation; either
#  version 2 of the License, or (at your option) any later version.
# 
#  This library is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#  Lesser General Public License for more details.
# 
#  You should have received a copy of the GNU Lesser General Public
#  License along with this library; if not, write to the Free 
#  Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, 
#  MA  02111-1307  USA
#             
#  For further information, see <http://www.nexusformat.org/>
#
#====================================================================

import os
import platform
import sys
import re
import shutil
from socket import gethostname

import nexus_scons_utils

Import('env')
myenv = env.Clone()
myenv.Append(CPPPATH=['#/include'])
shared_list = env['SHARED_LIST']
static_list = env['STATIC_LIST']
libList = env['MYLIBLIST']
libDirList = env['MYLIBDIRLIST']
shlibList = env['MYSHLIBLIST']
shlibDirList = env['MYSHLIBDIRLIST']

myenv_dynamic = myenv.Clone()
myenv_dynamic.Append(LIBS=shlibList)
myenv_dynamic.Append(LIBPATH=shlibDirList)
myenv_dynamic.Append(LIBPATH='#Bin/Shared')
shared = myenv_dynamic.Program('nxbrowse',['NXbrowse.c'],PDB='nxbrowse.pdb')
#shared = myenv_dynamic.Program('nxconvert',['nxconvert.c','nxconvert_common.c'],PDB='nxconvert.pdb')
#shared = myenv_dynamic.Program('nxvalidate',['nxvalidate.c','nxconvert_common.c'],PDB='nxvalidate.pdb')

myenv_static = myenv.Clone()
myenv_static.Append(LIBS=libList)
myenv_static.Append(LIBPATH=libDirList)
myenv_static.Append(LIBPATH='#Bin/Static')
#myenv_static.Append(LINKFLAGS=['-static'])
static = myenv_static.Program('nxbrowse_static', ['NXbrowse.c'], PDB='nxbrowse_static.pdb')
#static = myenv_static.Program('nxconvert_static',['nxconvert.c','nxconvert_common.c'],PDB='nxconvert_static.pdb')
#static = myenv_static.Program('nxvalidate_static',['nxvalidate.c','nxconvert_common.c'],PDB='nxvalidate_static.pdb')

retval = { 'shared': shared, 'static' : static }
Return('retval')
