.TH NXVALIDATE 1 "October 2011"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
nxvalidate \- Validate a NeXus file
.SH SYNOPSIS
.B nxvalidate
.SH DESCRIPTION
.B nxvalidate
will validate a nexus file against an application definition. It relies on nxconvert 
being installed. For more information see the help information in the gui.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics,
.\" respectively.
.SH SEE ALSO
.BR nxconvert(1),
.BR nxdir (1),
.BR nxsummary (1),
.BR nxtranslate (1),
.BR http://www.nexusformat.org
.SH AUTHOR
.B nxvaldate
was originally written by Freddie Akeroyd, Stuart Campbell, Peter Peterson, 
and Stephen Rankin and may be used by others.
