#!/bin/sh
#
# $Id$
#
# Install additional libraries for NeXus
#
rpm -Uvh http://nexus.isis.rl.ac.uk/kits/rpm/szip-2.0-1.i386.rpm
rpm -Uvh http://nexus.isis.rl.ac.uk/kits/rpm/hdf-4.2.1-1.i386.rpm
rpm -Uvh http://nexus.isis.rl.ac.uk/kits/rpm/hdf5-1.6.4-1.i386.rpm
rpm -Uvh http://nexus.isis.rl.ac.uk/kits/rpm/mxml-2.2.2-1.i386.rpm
#
