.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH NXSUMMARY 1 "July 2011"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
nxsummary \- generate summary of  a NeXus file
.SH SYNOPSIS
.B nxdir
.RI [ --xml ] 
.RI [ --value <label> ] 
.RI [ --writeconfig <file> ] 
.RI [ --config <file> ] 
.RI [ --verbose ] 
.RI [ -h ] 
.RI [ -v ] 
.RI [ -- ] 
.RI filename
.RI ...
.SH DESCRIPTION
.B nxsummary
generates a customised summary of NeXus files.
.PP
This program relies heavily on the configuration file specified or 
defaulting that on what is located in
.RI ${HOME}/.nxsummary.conf
or 
.RI /etc/nxsummary.conf
.SH CONFIGURATION FILE
A sample
configuration file can be obtained using the "--writeconfig" flag.
Each
"item" tag in the file describes a node to print from the NeXus file.
The "path" attribute describes where in the NeXus file to get
information from. The "label" attributes is what will be printed when
showing the value of the specified field. The optional "operation"
attribute provides for certain operations to be performed on the data
before printing out the result.
.PP
Valid operations are:
.TP
.B   COUNT 
The number of elements in the requested field.
.TP
.B   DIMS 
The dimensions of the requested field.
.TP
.B   SUM
Add together all of the array elements and print the result.
.TP
.B   UNITS:<new units> 
Specify the units to print the result in.
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics,
.\" respectively.
.SH OPTIONS
.TP
.B  -xml
Print result as xml.
.TP
.B --value \fIlabel\fP
Get value of the item pointed to by the label.
.TP
.B --writeconfig \fIfile\fP
Write the default configuration out to a file.
.TP
.B --config \fIfile\fP
Use specified configuration file.
.TP
.B --verbose
Be verbose.
.TP
.B -- 
Ignore following flags (treat as filenames).
.TP
.B -v|--version
Show version information.
.TP
.B -h|--help
Show usage information.
.SH SEE ALSO
.BR nxbrowse (1)
.BR http://www.nexusformat.org
.br
.SH AUTHOR
nxsummary was originally written by P. F. Peterson 
.nh
<petersonpf@ornl.gov>
.hy
.PP
This manual page was written by Tobias Richter 
.nh
<Tobias.Richter@diamond.ac.uk>
.hy
and may be used by others.
