/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class neutron_nexus_NexusFile */

#ifndef _Included_neutron_nexus_NexusFile
#define _Included_neutron_nexus_NexusFile
#ifdef __cplusplus
extern "C" {
#endif
#undef neutron_nexus_NexusFile_NXACC_READ
#define neutron_nexus_NexusFile_NXACC_READ 1L
#undef neutron_nexus_NexusFile_NXACC_RDWR
#define neutron_nexus_NexusFile_NXACC_RDWR 2L
#undef neutron_nexus_NexusFile_NXACC_CREATE
#define neutron_nexus_NexusFile_NXACC_CREATE 3L
#undef neutron_nexus_NexusFile_NXACC_CREATE4
#define neutron_nexus_NexusFile_NXACC_CREATE4 4L
#undef neutron_nexus_NexusFile_NXACC_CREATE5
#define neutron_nexus_NexusFile_NXACC_CREATE5 5L
#undef neutron_nexus_NexusFile_NXACC_CREATEXML
#define neutron_nexus_NexusFile_NXACC_CREATEXML 6L
#undef neutron_nexus_NexusFile_NX_UNLIMITED
#define neutron_nexus_NexusFile_NX_UNLIMITED 0L
#undef neutron_nexus_NexusFile_NX_FLOAT32
#define neutron_nexus_NexusFile_NX_FLOAT32 5L
#undef neutron_nexus_NexusFile_NX_FLOAT64
#define neutron_nexus_NexusFile_NX_FLOAT64 6L
#undef neutron_nexus_NexusFile_NX_INT8
#define neutron_nexus_NexusFile_NX_INT8 20L
#undef neutron_nexus_NexusFile_NX_BINARY
#define neutron_nexus_NexusFile_NX_BINARY 20L
#undef neutron_nexus_NexusFile_NX_UINT8
#define neutron_nexus_NexusFile_NX_UINT8 21L
#undef neutron_nexus_NexusFile_NX_BOOLEAN
#define neutron_nexus_NexusFile_NX_BOOLEAN 21L
#undef neutron_nexus_NexusFile_NX_INT16
#define neutron_nexus_NexusFile_NX_INT16 22L
#undef neutron_nexus_NexusFile_NX_UINT16
#define neutron_nexus_NexusFile_NX_UINT16 23L
#undef neutron_nexus_NexusFile_NX_INT32
#define neutron_nexus_NexusFile_NX_INT32 24L
#undef neutron_nexus_NexusFile_NX_UINT32
#define neutron_nexus_NexusFile_NX_UINT32 25L
#undef neutron_nexus_NexusFile_NX_CHAR
#define neutron_nexus_NexusFile_NX_CHAR 4L
#undef neutron_nexus_NexusFile_NX_COMP_NONE
#define neutron_nexus_NexusFile_NX_COMP_NONE 100L
#undef neutron_nexus_NexusFile_NX_COMP_LZW
#define neutron_nexus_NexusFile_NX_COMP_LZW 200L
#undef neutron_nexus_NexusFile_NX_COMP_RLE
#define neutron_nexus_NexusFile_NX_COMP_RLE 300L
#undef neutron_nexus_NexusFile_NX_COMP_HUF
#define neutron_nexus_NexusFile_NX_COMP_HUF 400L
#undef neutron_nexus_NexusFile_MAXNAMELEN
#define neutron_nexus_NexusFile_MAXNAMELEN 64L
/*
 * Class:     neutron_nexus_NexusFile
 * Method:    init
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_neutron_nexus_NexusFile_init
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     neutron_nexus_NexusFile
 * Method:    close
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_neutron_nexus_NexusFile_close
  (JNIEnv *, jobject, jint);

/*
 * Class:     neutron_nexus_NexusFile
 * Method:    nxflush
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_neutron_nexus_NexusFile_nxflush
  (JNIEnv *, jobject, jint);

/*
 * Class:     neutron_nexus_NexusFile
 * Method:    nxmakegroup
 * Signature: (ILjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_neutron_nexus_NexusFile_nxmakegroup
  (JNIEnv *, jobject, jint, jstring, jstring);

/*
 * Class:     neutron_nexus_NexusFile
 * Method:    nxopengroup
 * Signature: (ILjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_neutron_nexus_NexusFile_nxopengroup
  (JNIEnv *, jobject, jint, jstring, jstring);

/*
 * Class:     neutron_nexus_NexusFile
 * Method:    nxopenpath
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_neutron_nexus_NexusFile_nxopenpath
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     neutron_nexus_NexusFile
 * Method:    nxopengrouppath
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_neutron_nexus_NexusFile_nxopengrouppath
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     neutron_nexus_NexusFile
 * Method:    nxclosegroup
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_neutron_nexus_NexusFile_nxclosegroup
  (JNIEnv *, jobject, jint);

/*
 * Class:     neutron_nexus_NexusFile
 * Method:    nxmakedata
 * Signature: (ILjava/lang/String;II[I)V
 */
JNIEXPORT void JNICALL Java_neutron_nexus_NexusFile_nxmakedata
  (JNIEnv *, jobject, jint, jstring, jint, jint, jintArray);

/*
 * Class:     neutron_nexus_NexusFile
 * Method:    nxmakecompdata
 * Signature: (ILjava/lang/String;II[II[I)V
 */
JNIEXPORT void JNICALL Java_neutron_nexus_NexusFile_nxmakecompdata
  (JNIEnv *, jobject, jint, jstring, jint, jint, jintArray, jint, jintArray);

/*
 * Class:     neutron_nexus_NexusFile
 * Method:    nxopendata
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_neutron_nexus_NexusFile_nxopendata
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     neutron_nexus_NexusFile
 * Method:    nxclosedata
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_neutron_nexus_NexusFile_nxclosedata
  (JNIEnv *, jobject, jint);

/*
 * Class:     neutron_nexus_NexusFile
 * Method:    nxcompress
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_neutron_nexus_NexusFile_nxcompress
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     neutron_nexus_NexusFile
 * Method:    nxgetdata
 * Signature: (I[B)V
 */
JNIEXPORT void JNICALL Java_neutron_nexus_NexusFile_nxgetdata
  (JNIEnv *, jobject, jint, jbyteArray);

/*
 * Class:     neutron_nexus_NexusFile
 * Method:    nxgetslab
 * Signature: (I[I[I[B)V
 */
JNIEXPORT void JNICALL Java_neutron_nexus_NexusFile_nxgetslab
  (JNIEnv *, jobject, jint, jintArray, jintArray, jbyteArray);

/*
 * Class:     neutron_nexus_NexusFile
 * Method:    nxgetattr
 * Signature: (ILjava/lang/String;[B[I)V
 */
JNIEXPORT void JNICALL Java_neutron_nexus_NexusFile_nxgetattr
  (JNIEnv *, jobject, jint, jstring, jbyteArray, jintArray);

/*
 * Class:     neutron_nexus_NexusFile
 * Method:    nxputdata
 * Signature: (I[B)V
 */
JNIEXPORT void JNICALL Java_neutron_nexus_NexusFile_nxputdata
  (JNIEnv *, jobject, jint, jbyteArray);

/*
 * Class:     neutron_nexus_NexusFile
 * Method:    nxputslab
 * Signature: (I[B[I[I)V
 */
JNIEXPORT void JNICALL Java_neutron_nexus_NexusFile_nxputslab
  (JNIEnv *, jobject, jint, jbyteArray, jintArray, jintArray);

/*
 * Class:     neutron_nexus_NexusFile
 * Method:    nxputattr
 * Signature: (ILjava/lang/String;[BI)V
 */
JNIEXPORT void JNICALL Java_neutron_nexus_NexusFile_nxputattr
  (JNIEnv *, jobject, jint, jstring, jbyteArray, jint);

/*
 * Class:     neutron_nexus_NexusFile
 * Method:    nxgetinfo
 * Signature: (I[I[I)V
 */
JNIEXPORT void JNICALL Java_neutron_nexus_NexusFile_nxgetinfo
  (JNIEnv *, jobject, jint, jintArray, jintArray);

/*
 * Class:     neutron_nexus_NexusFile
 * Method:    nxsetnumberformat
 * Signature: (IILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_neutron_nexus_NexusFile_nxsetnumberformat
  (JNIEnv *, jobject, jint, jint, jstring);

/*
 * Class:     neutron_nexus_NexusFile
 * Method:    nextentry
 * Signature: (I[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_neutron_nexus_NexusFile_nextentry
  (JNIEnv *, jobject, jint, jobjectArray);

/*
 * Class:     neutron_nexus_NexusFile
 * Method:    nextattr
 * Signature: (I[Ljava/lang/String;[I)I
 */
JNIEXPORT jint JNICALL Java_neutron_nexus_NexusFile_nextattr
  (JNIEnv *, jobject, jint, jobjectArray, jintArray);

/*
 * Class:     neutron_nexus_NexusFile
 * Method:    nxgetgroupid
 * Signature: (ILneutron/nexus/NXlink;)V
 */
JNIEXPORT void JNICALL Java_neutron_nexus_NexusFile_nxgetgroupid
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     neutron_nexus_NexusFile
 * Method:    nxgetdataid
 * Signature: (ILneutron/nexus/NXlink;)V
 */
JNIEXPORT void JNICALL Java_neutron_nexus_NexusFile_nxgetdataid
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     neutron_nexus_NexusFile
 * Method:    nxmakelink
 * Signature: (ILneutron/nexus/NXlink;)V
 */
JNIEXPORT void JNICALL Java_neutron_nexus_NexusFile_nxmakelink
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     neutron_nexus_NexusFile
 * Method:    nxopensourcepath
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_neutron_nexus_NexusFile_nxopensourcepath
  (JNIEnv *, jobject, jint);

/*
 * Class:     neutron_nexus_NexusFile
 * Method:    debugstop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_neutron_nexus_NexusFile_debugstop
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
