#!/sbin/sh
#------------------------------------------------------------------------
# shell script for running the test program for the Java NeXus API
#
# Version for DigitalUnix4.0D
#
# Mark Koennecke, October 2000
#------------------------------------------------------------------------
java -mx32m -classpath  /usr/lib/classes.zip:../:. \
 -Dneutron.nexus.JNEXUSLIB=../bin/du40/libjnexus.so TestJapi $1 $2
 
