#ifdef DEBUG_NXTRANSLATE
#define DEBUG1_NXTRANSLATE
#endif

#ifdef DEBUG3_NXTRANSLATE
#define DEBUG2_NXTRANSLATE
#define DEBUG3_XML_PARSER
#endif

#ifdef DEBUG2_NXTRANSLATE
#define DEBUG1_NXTRANSLATE
#endif

#ifdef DEBUG1_NXTRANSLATE
#define DEBUG1_XML_PARSER
#define DEBUG1_NEXUS_UTIL
#endif
